### ISSUE TITLE
This code uses Google Analytics?

### ISSUE THREAD

**Issue by chmac** [corbindavenport/link-cleaner#2]
I just spotted this in the source code:

https://github.com/corbindavenport/link-cleaner/blob/9719529b9dbbcf8c9b356aaed9e39e685064334f/js/cleaner.js#L4-L6

This link cleaning tool itself uses Google Analytics, is that correct?

If so, I think I'll likely withdraw my offer to submit a PR in #1. I'm not open to supporting software which advertises a focus on privacy and simultaneously uses Google Analytics. Perhaps there's a compelling reason, or you have a difference of opinion, I'm happy to discuss, but I also want to be upfront with my opinion that the 2 things are not compatible.

**Comment by corbindavenport** [comment]
I use Google Analytics to track basic page views, so I can determine how often Link Cleaner gets used and when it makes sense for me to work on it. Switching to the more privacy-respecting [Plausible Analytics](https://www.patreon.com/corbindavenport#:~:text=Goals) is one of my Patreon goals, since it's a paid product and GA is free.

**Comment by corbindavenport** [comment]
Closing this because Link Cleaner has now switched to Plausible Analytics: https://github.com/corbindavenport/link-cleaner/commit/32788412146156d5d858edb111853cb721d59d5f
